In [3]:
import numpy as np
fold_size = 10
k = 5

x = np.arange(50)

for j in range(k):
    # 本折的样本索引区间 [j*fold_size, (j+1)*fold_size)
    idx = slice(j * fold_size, (j + 1) * fold_size)
    print(idx)
    print(x[idx])

slice(0, 10, None)
[0 1 2 3 4 5 6 7 8 9]
slice(10, 20, None)
[10 11 12 13 14 15 16 17 18 19]
slice(20, 30, None)
[20 21 22 23 24 25 26 27 28 29]
slice(30, 40, None)
[30 31 32 33 34 35 36 37 38 39]
slice(40, 50, None)
[40 41 42 43 44 45 46 47 48 49]
