In [19]:
import torch 

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [20]:
x.requires_grad_(True)
x.grad

In [21]:
y = 2*torch.dot(x,x)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [22]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [23]:
x.grad == 4*x

tensor([True, True, True, True])

In [30]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [31]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [35]:
x.grad.zero_()
y = x * x
u = y.detach()

z = u * x
z.sum().backward()
u, x.grad

(tensor([0., 1., 4., 9.]), tensor([0., 1., 4., 9.]))