## Manually calculate softmax()

In [1]:
import torch
from IPython import display
from d2l import torch as d2l

batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

we know image is 28*28 = 784 px, and output is one of 10.

In [8]:
num_inputs = 784
num_outputs = 10

# initialization(not have to, pytorch will initial for us)
W = torch.normal(0,0.01, size = (num_inputs, num_outputs), requires_grad=True)
b = torch.zeros(num_outputs, requires_grad=True)

simple review

In [20]:
X = torch.tensor([[1,2,3], [4,5,6]])
print(X.sum(0, keepdim=True), X.sum(0,keepdim=True).shape)
X.sum(1, keepdim=True)


tensor([[5, 7, 9]]) torch.Size([1, 3])


tensor([[ 6],
        [15]])

In [19]:
# implement softmax
def softmax(X: torch.Tensor) -> torch.Tensor:
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdim=True)
    return X_exp / partition

In [ ]:
# check if softmax() correct
X = torch.normal(0,1, (2,5))
X_prob = softmax(X)
X_prob, X_prob.sum(1)

(tensor([[0.2678, 0.1170, 0.1771, 0.1667, 0.2713],
         [0.3208, 0.1983, 0.0329, 0.3129, 0.1351]]),
 tensor([1.0000, 1.0000]))

In [25]:
def net(X: torch.Tensor) -> torch.Tensor:
    return softmax(torch.matmul(X.reshape((-1, W.shape[0])), W) + b)

In [26]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y_hat[[0, 1], y]

tensor([0.1000, 0.5000])

In [28]:
def cross_entropy(y_hat, y):
    return -torch.log(y_hat[range(len(y_hat)), y])

cross_entropy(y_hat, y)

tensor([2.3026, 0.6931])

In [30]:
def accuracy(y_hat, y):  #@save
    """计算预测正确的数量"""
    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
        y_hat = y_hat.argmax(axis=1)
    cmp = y_hat.type(y.dtype) == y
    return float(cmp.type(y.dtype).sum())

accuracy(y_hat, y) / len(y)

0.5

In [3]:
import numpy as np
x = np.random.rand(3, 2)

y = np.sum(x, axis=0, keepdims=True)
y.shape

(1, 2)